### ISSUE TITLE
Provide AbstractCSVDataProvider constructor that uses URL

### ISSUE THREAD

**Issue by rjlasko** [liefke/org.fastnate#26]
So i found that the AbstractCsvDataProvider is very nice, except that it must load its data from a File, which is validated for its existence and all that.  Too bad because I like the ability to load from a CSV, but want to be able to pull this content from a file embedded on a JAR, instead of a standalone file.

This would be nice...
`public AbstractCsvStreamDataProvider(final URL resourceURL) `

**Comment by liefke** [comment]
You are right, `AbstractCsvDataProvider` was developed with files in mind and is neglected since then. In our projects we use a custom DataProvider for CSV files from resources. 

This change won't be as easy as it seems, because the AbstractCsvDataProvider should still provide the ability to read all CSV files from a whole directory. 

I guess I will split the functionality into two parts: 

1. A DataProvider where I can map columns to properties.
2. A ColumnReader with different implementations. 

That way I can either read the columns from a single CSV file (from an URL), from a directory, or even from an Excel file without having to change the DataProvider.

**Comment by liefke** [comment]
It took some while, but there is now an API to parse files from the class path or even from other URLs. The CSV support has moved to the `fastnate-csv` module. Check [OrganisationData.java](/liefke/org.fastnate/blob/master/fastnate-examples/src/main/java/org/fastnate/examples/data/OrganisationData.java) from the [fastnate-examples](/liefke/org.fastnate/blob/master/fastnate-examples/) project for the usage of the new API.

If you still need to read the file from an URL, you can use `importer.importFile(new UrlDataFile(url))`.
