### ISSUE TITLE
ConnectedStatementsWriter does not respect autocommit=false of given connectionn

### ISSUE THREAD

**Issue by apenski** [liefke/org.fastnate#42]
In the constructor the autocommit of a given connection is forcibly set according to GeneratorDialect#isFastInTransaction() configuration. However, if the supplied connection was already used within a transaction any action prio fastnate is commited.

I would expect, that fastnate respects the transaction. 

Could you please also check whether this code is a duplicate of EntityImporter#importData(connection)

**Comment by liefke** [comment]
That is true, I didn't think about the usecase, that someone is importing data in a surrounding transaction.

I removed any transaction specific stuff from the `ConnectedStatementsWriter` - it leaves the transaction untouched, unless someone is calling `flush()` which will commit the transaction.

`EntityImporter.importData(Connection)` will still try to open and commit a transaction if none is open and the current database is faster with a long running transaction. If any exception occurs during the import it will try a rollback instead of a commit. If a transaction is already open at the beginning, nothing happens.
