### ISSUE TITLE
Fastnate - Spring Boot Generate the whole schema based on the entities

### ISSUE THREAD

**Issue by yurijserrano** [liefke/org.fastnate#49]
Good Morning

I have three questions related to fastnate.

The first one is if the Fastnate can just be used to populate the database.

The second one is how I can achieve this because I've read all the documentation and even after adding all the maven dependencies and creating the class none data.sql file was generated.

[LINK I](https://github.com/liefke/org.fastnate/wiki/FirstSteps)

[LINK II](https://github.com/liefke/org.fastnate/blob/master/fastnate-examples/src/main/java/org/fastnate/examples/data/PersonData.java)

The third one is if it's possible to generate the whole schema of the database as it's possible with the Spring JPA with the configuration below:

`spring.jpa.properties.javax.persistence.schema-generation.create-source=metadata
spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=create.sql`

I've seen a person that mentioned fastnate here but reading it wasn't clear if fastnate can do this or not.

[LINK III](https://stackoverflow.com/questions/36966337/how-to-generate-a-ddl-creation-script-with-a-modern-spring-boot-data-jpa-and-h)

Thanks for the support

**Comment by liefke** [comment]
Hi Yuri,

thank you for your interest in Fastnate.

Yes Fastnate is only used for populating the database. As we always use Hibernate (see #1), we use _hibernate-tools_ to generate our offline schema SQLs. If you are interested in how to achieve this, I would be happy to go more into detail. We even use the combination hibernate-tools and Fastnate for some production projects, where the difference between previous version and current version of the SQL files helps us to generate the appropriate change scripts.

I added a comment to the Stackoverflow answer in your [LINK III](https://stackoverflow.com/questions/36966337/how-to-generate-a-ddl-creation-script-with-a-modern-spring-boot-data-jpa-and-h/59546362#59546362) to make this clear.

If you stick to the [examples project](https://github.com/liefke/org.fastnate/tree/master/fastnate-examples) you should find a `target/classes/data.sql` in the end. How did you invoke Maven? With `mvn package`, `mvn process-classes` or `mvn org.fastnate:fastnate-maven-plugin:import-data` (each should work)? Please note, that a simple `mvn compile` won't work, because Fastnate needs the compiled classes to run and is bound therefore to the later `process-classes` phase. I've adjusted the _First Steps_ to make that clear.

If you still don't get it to work, is there any log you can provide?

**Comment by yurijserrano** [comment]
**We use hibernate-tools to generate our offline schema SQLs. If you are interested in how to achieve this, I would be happy to go more into detail.**

**We even use the combination hibernate-tools and Fastnate for some production projects**

I would love it @liefke, because I really enjoyed the main idea behind the fastnate, that automates all of this SQL process just focusing on the implementation of the code.

I don't know if is hard to implement, but would be great if fastnate generate the whole schema of the database plus the data, would help a lot, opening several possibilities for some automation.

Nowadays, I am using the Intellij Ultimate version and the unique way that I know to generate the schema from the entities it's using the configurations that I showed to you earlier, so knowing other ways in how to create the schema from the entities and vice versa would be great.

**How did you invoke Maven? With mvn package, mvn process-classes or mvn org.fastnate:fastnate-maven-plugin:import-data (each should work)?**

Thank you for the clarifications @liefke, I was using `mvn package` but my mistake was not included the package in the maven plugin, after putting the packages worked like a charm.

But testing the commands a new question comes, I was able to generate the data.sql file normally with `mvn package` and `mvn process-classes`, as you can see below:

![mvn process classes](https://user-images.githubusercontent.com/14169134/78944103-8ba74d80-7a93-11ea-9f8f-00a76ca8f26e.png)

![mvn package](https://user-images.githubusercontent.com/14169134/78944110-9235c500-7a93-11ea-88c7-7bdb0b81b661.png)


![tablegenerated](https://user-images.githubusercontent.com/14169134/78944155-a679c200-7a93-11ea-9c38-019b2564fdd9.png)

But when I run the command `mvn org.fastnate:fastnate-maven-plugin:import-data` none data was written in the data.sql, I've tested two cases:

1. Executing the command `mvn process-classes`, so the data.sql was generated properly, deleting this data.sql and running the `mvn org.fastnate:fastnate-maven-plugin:import-data` 

2. Executing the command `mvn process-classes` and without deleting the data.sql running the command `mvn org.fastnate:fastnate-maven-plugin:import-data` 


In both scenarios, the data.sql was generated but none insert was added.

Below you can see the images:

![tablegenerated01](https://user-images.githubusercontent.com/14169134/78944260-de810500-7a93-11ea-80f9-b903c843a233.png)

Despite this, I have just two more questions.

First one, I've seen in the documentation that is possible to generate the data.sql from the command line but after executing the command I've got this:

![fastnatejart](https://user-images.githubusercontent.com/14169134/78944471-5c451080-7a94-11ea-9293-cd53694041c2.png)

COMMAND: `java -cp CRITTER/Family\ -\ Demo\ Using\ ModelMapper\ and\ Orika/target/ fastnate-data.jar;fastnate-generator.jar -Dfastnate.data.provider.packages=.com.example.family.demo.son.domain org.fastnate.data.EntityImporter data.sql`


I've included the fastnate jars in the folder as you can see below:

![fastnatejar2](https://user-images.githubusercontent.com/14169134/78944483-61a25b00-7a94-11ea-8b92-32b37cb51b89.png)

Could it be a bug?

The second one is that I've seen these issues related to the `EntitySqlGenerator` or `WriterEntitySqlGenerator` on these topics:


[ISSUE - 17](https://github.com/liefke/org.fastnate/issues/17)
[ISSUE - 31](https://github.com/liefke/org.fastnate/issues/31)
[ISSUE - 19](https://github.com/liefke/org.fastnate/issues/19)

![fastnateproblem](https://user-images.githubusercontent.com/14169134/78944640-b9d95d00-7a94-11ea-81f7-649ee85e7321.png)

![problem](https://user-images.githubusercontent.com/14169134/78944658-c3fb5b80-7a94-11ea-9708-af029cb865e6.png)

![writesqlgenerator](https://user-images.githubusercontent.com/14169134/78944667-ca89d300-7a94-11ea-8056-f76e3c6f28d8.png)

And even using java 8 it's not resolving these classes.


Thanks for all the support and attention

**Comment by liefke** [comment]
Hi Yuri,

I will try to answer your questions, even if some of them are common Java or Maven problems and not specific to Fastnate at all:

1. I described the generation of the `schema.sql` with _Hibernate_ in the [HowTos](https://github.com/liefke/org.fastnate/wiki/HOWTO#how-to-use-fastnate-after-going-to-production-mode) now. _Fastnate_ will never create the schema.sql for you, because we would "reinvent the wheel" - most of the JPA frameworks are already able to do this.
2. Please remember that any `<configuration>` that you add inside an `<execution>` element is specific only to that execution. If you would like to define the configuration for every execution of the plugin (even for those from the command line), you have to add it directly inside the `<plugin>` section:

        <plugin>
            <groupId>org.fastnate</groupId>
            <artifactId>fastnate-maven-plugin</artifactId>
            <version>...</version>
            <configuration>
                <packages>...</packages>
            </configuration>
            ...
         </plugin>

Another option is to use a profile, an example for this is the `schema-generation` profile in the [HowTos](https://github.com/liefke/org.fastnate/wiki/HOWTO#how-to-use-fastnate-after-going-to-production-mode).
3. The error message for your `java -cp ...` is quite clear: Java thinks, that `fastnate-data.jar` is the name of the main class, because you forgot the `;` between your target folder and the JAR.
4. If you are extending the `AbstractDataProvider`, you don't need to instantiate the generator at all, it is already generated for you and provided to `writeEntities` (see the default implementation in `AbstractDataProvider`).
5. You don't need to think about #17, #19 or #31, as long as you only generate new entities with your data provider.

**Comment by yurijserrano** [comment]
Sorry for the delay @liefke 

I was really busy this week.

But I will test the procedures tomorrow or Friday, so this way I can provide thoughtful feedback.

Thank you so much for your attention and help

**Comment by liefke** [comment]
@yurijserrano Can I close the ticket or is this still an issue?

**Comment by yurijserrano** [comment]
Good Morning @liefke 


Of course, thank you so much for your cooperation and help.

I will do some more tests and any new problem I will open another ticket.


Have a nice day and weekend.
