### ISSUE TITLE
[Question] Is it possible to force write entities which already have an id?

### ISSUE THREAD

**Issue by schowave** [liefke/org.fastnate#60]
In my entity there is the id with the following annotations:

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID")
    protected Long id;

For testdata with fastnate, I want to set the id explicitly in the entity.
But when I want to write the data via:

    generator.write(entity)

it is not written out. If the Id is not set beforehand, it will be written. Is it possible to force write insert statement with this setup?

**Comment by liefke** [comment]
To identify already written entities, Fastnate uses the ID as marker when `@GeneratedValue` is used. 
Fastnate does usually not keep track of all written entities. I've got imports with millions of entities - imagine what would happen, if Fastnate stores all of them.

On the other hand it does not make many sense to insert a value into an IDENTITY column anyway. Some databases even prohibit it, because the database wouldn't know where to continue counting. I'm curious, why you even trying to do something like that?

Nevertheless I could easily offer this as a feature, because Fastnate does need to keep track already, if no `@GeneratedValue` is used. So I could add a configuration option to use that feature for generated values, too (turned off by default, as this is slower than the "check for ID" approach). But could you add some details to your use case first?

**Comment by schowave** [comment]
I am generating some basic data for the database in the beginning. This should be done via sql script so that the admins can verify the inserted entities in the script. For some other database tests, i don't use this feature, but I let the JPA Repository handle the creation of the entities by itself. But this only works without issue, when I use generated Id values. Furthermore, in the future it might be possible, that the database will be extended with values from the application. Then, I do not want to track the Ids by myself, but those should be inserted by the database. 

If you could add a feature like this, it would help me a lot! Thank you for the fast answer and the support!

**Comment by liefke** [comment]
What kind of database are you using? Did you check if it supports to set the value of an identity column in an `INSERT` statement? Otherwise my option would be of no use.

And I don't get why you need to set an ID, even without it the admins could easily verify the inserted entities. At the end they get the same ID that they would get if the JPA repository would create the entities.

**Comment by schowave** [comment]
Nevermind, I solved the issue by using relativeIds, so no need for the "force-write-entity" support. Thank you for your support!
